version: "3.5"

services:
    docs:
        build:
            context: .
            dockerfile: docs.Dockerfile
        image: mcano/docs
        ports:
        - 8000:80

    api:
        build:
            context: .
            dockerfile: api.Dockerfile
        image: mcano/api
        ports:
        - 3000:3000