site_name: Examen Parcial 2

nav:
    - Instrucciones: index.md
    - Parte1 - Cards: parte1.md
    - Parte2 - Home: parte2.md
    - Parte3 - About: parte3.md
    - Fin - Entrega: entrega.md
    - Extra Resources: resources.md
    - Timer ⌛️: timer.md

theme: material

plugins:
    - search
    - markdownextradata: {}

extra:
  api:
    url: http://38c6b03a.ngrok.io/api/db
    management: http://38c6b03a.ngrok.io/api/management
    team: http://38c6b03a.ngrok.io/api/team